spring:
  application:
    name: mindle

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # sql 로그 출력
    properties:
      hibernate:
        format_sql: true

firebase:
  config-path: classpath:mindle-secret.json

logging:
  level:
    org.hibernate.SQL: DEBUG           # Hibernate 실행 SQL
    org.hibernate.type.descriptor.sql: TRACE   # SQL 에 바인딩되는 파라미터 값도 출력

decorator: #SQL 로그 이쁘게 라이브러리
  datasource:
    p6spy:
      enable-logging: true
      multiline: true   # 줄바꿈 예쁘게
      logging: slf4j    # 로깅 방식

spring-doc: # swagger 설정
  swagger-ui:
    tags-sorter: alpha         # 태그 알파벳 정렬
    operations-sorter: method  # 메소드 정렬
    doc-expansion: none        # 접은 상태로 표시

ncp:
  object:
    endpoint: https://kr.object.ncloudstorage.com
    region: kr-standard
    access-key: ${NCP_ACCESS_KEY}
    secret-key: ${NCP_SECRET_KEY}
    bucket-name: ${NCP_BUCKET_NAME}
